---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-kube-network-metrics
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - nodes
      - pods
      - pods/exec
    verbs:
      - create
      - get
      - list
